"""
Generate the Chinese vocab.h for the ESP32 firmware (isolated from English).

Same format as src/gen_assets.py produces for the English BPE tokenizer, but
from the Chinese CharTokenizer: each token is one character, and VOCAB_BLOB
stores the UTF-8 bytes with VOCAB_OFF offsets. The firmware's emit() then
Serial.write()s the decoded bytes directly.

Usage:
    uv run python chinese/gen_vocab.py
    uv run python chinese/gen_vocab.py --out firmware/esp32_llm_zh/vocab.h
"""

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from chinese.tokenizer import CharTokenizer  # noqa: E402


def main():
    ap = argparse.ArgumentParser(description="Generate Chinese vocab.h for ESP32 firmware")
    ap.add_argument("--tokenizer", default=str(PROJECT_ROOT / "data_chinese" / "tokenizer.json"))
    ap.add_argument("--out", default=str(PROJECT_ROOT / "firmware" / "esp32_llm_zh" / "vocab.h"))
    args = ap.parse_args()

    tok = CharTokenizer.load(args.tokenizer)
    V = tok.vocab_size
    print(f"tokenizer: {V} tokens (user={tok.USER}, assist={tok.ASSIST}, end={tok.END})")

    # Build blob + offsets: each token id -> its UTF-8 bytes
    blob = bytearray()
    offs = [0]
    for i in range(V):
        ch = tok.itos.get(i, "")
        if not ch:
            blob.append(0)  # empty token -> single NUL byte (keeps offsets aligned)
            offs.append(len(blob))
            continue
        b = ch.encode("utf-8")
        blob.extend(b)
        offs.append(len(blob))

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write("// Generated by chinese/gen_vocab.py -- char id -> raw UTF-8 bytes.\n")
        f.write("#ifndef VOCAB_H\n#define VOCAB_H\n")
        f.write(f"#define VOCAB_N {V}\n")
        f.write(f"static const unsigned char VOCAB_BLOB[{len(blob)}] = {{\n")
        for i in range(0, len(blob), 20):
            f.write("  " + ",".join(str(b) for b in blob[i:i + 20]) + ",\n")
        f.write("};\n")
        f.write(f"static const int VOCAB_OFF[{len(offs)}] = {{\n")
        for i in range(0, len(offs), 20):
            f.write("  " + ",".join(str(o) for o in offs[i:i + 20]) + ",\n")
        f.write("};\n#endif\n")

    print(f"wrote {out}: {V} tokens, blob {len(blob)/1024:.1f} KB")

    # Verify round-trip for a few chars
    for i in [2, 3, tok.USER, tok.ASSIST, tok.END, 286, 147]:
        if i < V:
            s = blob[offs[i]:offs[i + 1]].decode("utf-8", errors="replace")
            print(f"  {i}: {s!r}")


if __name__ == "__main__":
    main()
