"""
Chinese model training for ESP32-LLM.

Thin wrapper that reuses the core model and training logic from src/,
but with Chinese-specific configuration and data paths.

Usage:
    uv run python chinese/train.py
    uv run python chinese/train.py --steps 100 --tag testrun
    uv run python chinese/train.py --d-model 96 --n-layers 6
"""

import argparse
import json
import math
import os
import sys
import time
from pathlib import Path

import numpy as np
import torch

# Add project root so we can import src modules
HERE = Path(__file__).resolve().parent
PROJECT_ROOT = HERE.parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.model import Config, TinyLM, make_model  # noqa: E402


# ---------------------------------------------------------------------------
#  Paths (isolated from English training)
# ---------------------------------------------------------------------------
DATA_DIR = PROJECT_ROOT / "data_chinese"
RUNS_DIR = PROJECT_ROOT / "runs_chinese"

# Suffix-less .bin files (generated by chinese/prepare.py)
TRAIN_BIN = DATA_DIR / "train.bin"
VAL_BIN = DATA_DIR / "val.bin"
TOKENIZER_JSON = DATA_DIR / "tokenizer.json"


# ---------------------------------------------------------------------------
#  Training helpers (adapted from src/train.py)
# ---------------------------------------------------------------------------

def get_device():
    if torch.backends.mps.is_available():
        return "mps"
    if torch.cuda.is_available():
        return "cuda"
    return "cpu"


class Batcher:
    """Memory-mapped batch loader for Chinese token sequences."""
    def __init__(self, path, batch_size, seq_len, device, seed=0):
        self.data = np.memmap(str(path), dtype=np.uint16, mode="r")
        self.bs, self.sl, self.device = batch_size, seq_len, device
        self.rng = np.random.default_rng(seed)

    def __call__(self):
        ix = self.rng.integers(0, len(self.data) - self.sl - 1, self.bs)
        x = np.stack([self.data[i: i + self.sl] for i in ix]).astype(np.int64)
        y = np.stack([self.data[i + 1: i + 1 + self.sl] for i in ix]).astype(np.int64)
        return torch.from_numpy(x).to(self.device), torch.from_numpy(y).to(self.device)


@torch.no_grad()
def evaluate(model, batcher, iters):
    model.eval()
    batcher.rng = np.random.default_rng(1234)
    losses = [model(*batcher())[1].item() for _ in range(iters)]
    model.train()
    return sum(losses) / len(losses)


def lr_at(step, total, peak, warmup):
    if step < warmup:
        return peak * (step + 1) / warmup
    p = (step - warmup) / max(1, total - warmup)
    return 0.1 * peak + 0.9 * peak * 0.5 * (1 + math.cos(math.pi * p))


# ---------------------------------------------------------------------------
#  Main
# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description="Train Chinese PLE model for ESP32-LLM")
    # Data
    ap.add_argument("--vocab-size", type=int, default=None,
                    help="Override vocab size (auto-detected from tokenizer if omitted)")
    # Architecture
    ap.add_argument("--arm", default="ple", choices=["baseline", "ple", "ple_notable"])
    ap.add_argument("--d-model", type=int, default=64)
    ap.add_argument("--n-layers", type=int, default=4)
    ap.add_argument("--n-heads", type=int, default=4)
    ap.add_argument("--ple-dim", type=int, default=64)
    ap.add_argument("--target-core", type=int, default=280000)
    # Training
    ap.add_argument("--steps", type=int, default=5000)
    ap.add_argument("--batch-size", type=int, default=16)
    ap.add_argument("--seq-len", type=int, default=256)
    ap.add_argument("--lr", type=float, default=1e-3)
    ap.add_argument("--warmup", type=int, default=100)
    ap.add_argument("--eval-every", type=int, default=250)
    ap.add_argument("--eval-iters", type=int, default=20)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--tag", default="zh")
    ap.add_argument("--device", default=None, help="Override device auto-detection")
    args = ap.parse_args()

    # Validate data
    if not TRAIN_BIN.exists():
        print(f"Training data not found: {TRAIN_BIN}")
        print("Run `uv run python chinese/prepare.py` first.")
        sys.exit(1)

    # Auto-detect vocab size from tokenizer
    if args.vocab_size is None:
        if TOKENIZER_JSON.exists():
            with open(TOKENIZER_JSON, encoding="utf-8") as f:
                tok_data = json.load(f)
            args.vocab_size = tok_data["vocab_size"]
        else:
            args.vocab_size = 8000
    print(f"Vocab size: {args.vocab_size}")

    # Setup
    torch.manual_seed(args.seed)
    device = args.device or get_device()
    os.makedirs(RUNS_DIR, exist_ok=True)
    print(f"Device: {device}")
    print(f"Data:   {DATA_DIR}")
    print(f"Runs:   {RUNS_DIR}")

    # Build model
    base = Config(
        seq_len=args.seq_len, ple_dim=args.ple_dim,
        vocab_size=args.vocab_size,
        d_model=args.d_model, n_layers=args.n_layers, n_heads=args.n_heads,
    )
    model = make_model(args.arm, args.target_core, base).to(device)
    budget = model.param_budget()
    cfg = model.cfg

    # Optimizer
    decay, no_decay = [], []
    for n, p in model.named_parameters():
        (no_decay if p.ndim < 2 or "table" in n or "tok_emb" in n else decay).append(p)
    opt = torch.optim.AdamW(
        [{"params": decay, "weight_decay": 0.1}, {"params": no_decay, "weight_decay": 0.0}],
        lr=args.lr, betas=(0.9, 0.95),
    )

    # Data loaders
    train_b = Batcher(TRAIN_BIN, args.batch_size, args.seq_len, device, seed=args.seed)
    val_b = Batcher(VAL_BIN, args.batch_size, args.seq_len, device, seed=1234)

    # Training loop
    name = f"{args.arm}-{args.tag}-s{args.seed}"
    history, best = [], float("inf")
    t0 = time.time()

    print(f"\n{'='*60}")
    print(f"Training {name}")
    print(f"  model: {budget['core']:,} core + {budget['table']:,} table + {budget['stream']:,} stream")
    print(f"  total params: {budget['total']:,}")
    print(f"{'='*60}\n")

    for step in range(args.steps):
        lr = lr_at(step, args.steps, args.lr, args.warmup)
        for g in opt.param_groups:
            g["lr"] = lr

        x, y = train_b()
        _, loss = model(x, y)
        opt.zero_grad(set_to_none=True)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        opt.step()

        if step % args.eval_every == 0 or step == args.steps - 1:
            vl = evaluate(model, val_b, args.eval_iters)
            best = min(best, vl)
            tok = (step + 1) * args.batch_size * args.seq_len
            history.append({"step": step, "tokens": tok, "train": loss.item(), "val": vl})
            elapsed = time.time() - t0
            print(
                f"{name} step {step:5d} | tok {tok / 1e6:6.1f}M | "
                f"train {loss.item():.4f} | val {vl:.4f} | "
                f"ppl {math.exp(vl):7.2f} | {elapsed:5.0f}s",
                flush=True,
            )

    # Save results
    result = {
        "arm": args.arm, "seed": args.seed, "tag": args.tag,
        "config": {k: v for k, v in cfg.__dict__.items()},
        "params": budget,
        "final_val": history[-1]["val"],
        "best_val": best,
        "final_ppl": math.exp(history[-1]["val"]),
        "tokens_seen": args.steps * args.batch_size * args.seq_len,
        "steps": args.steps,
        "wall_seconds": time.time() - t0,
        "history": history,
    }

    json_path = RUNS_DIR / f"{name}.json"
    pt_path = RUNS_DIR / f"{name}.pt"
    with open(json_path, "w") as f:
        json.dump(result, f, indent=2)
    torch.save({"cfg": cfg.__dict__, "state": model.state_dict()}, pt_path)

    print(f"\n{'='*60}")
    print(f"Done. Model saved to:")
    print(f"  {pt_path}")
    print(f"  {json_path}")
    print(f"  val={result['final_val']:.4f} ppl={result['final_ppl']:.2f}")
    print(f"  wall: {result['wall_seconds']:.0f}s")
    print(f"{'='*60}")
    print(f"\nNext: uv run python src/quantize.py --chinese --tag {args.tag}")
    print(f"      uv run python src/export.py {name}")


if __name__ == "__main__":
    main()
